<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
  </head>

  <body>
    <h1>Hello</h1>

    <?php
    $sentence = "This is generated by PHP";
    echo $sentence;
    ?>

    <p>Goodbye</p>

  </body>
</html>